# Generated by Django 2.0.1 on 2019-11-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('player_image', models.FileField(upload_to='')),
                ('player_jersey_number', models.IntegerField()),
                ('player_country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_matches_played', models.IntegerField(blank=True, null=True)),
                ('total_runs_scored', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('hundreds', models.IntegerField(blank=True, null=True)),
                ('no_of_catches', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('player_role', models.CharField(max_length=15)),
                ('no_of_wickets', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('team_logo', models.FileField(upload_to='')),
                ('club_state', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='pointtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricapp.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricapp.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='cricapp.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='cricapp.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_winner', to='cricapp.Team'),
        ),
    ]
